const socket=io();let current=null;const $=id=>document.getElementById(id);$('createBtn').onclick=()=>socket.emit('createRoom',{name:$('nameInput').value||'玩家A'});$('joinBtn').onclick=()=>socket.emit('joinRoom',{code:$('roomInput').value,name:$('nameInput').value||'玩家B'});$('startBtn').onclick=()=>socket.emit('startGame',{code:current.room.code});$('leaveBtn').onclick=()=>location.reload();$('nextBtn').onclick=()=>socket.emit('nextRound',{code:current.room.code});$('downloadCsvBtn').onclick=()=>downloadCSV();socket.on('created',({code})=>$('roomInput').value=code);socket.on('errorMessage',msg=>$('message').textContent=msg);socket.on('state',state=>{current=state;render()});
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}function rgbCss(rgb){return`rgb(${rgb[0]},${rgb[1]},${rgb[2]})`}function rgbText(rgb){return`RGB(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`}
function render(){show('game');const r=current.room;$('roomCode').textContent=r.code;$('yourSlot').textContent=current.you?current.you.slot:'?';$('playersText').textContent=`目前玩家：${r.players.map(p=>p.slot+' '+p.name).join('、')}`;$('waitingPanel').classList.toggle('hidden',r.started);$('gamePanel').classList.toggle('hidden',!r.started);$('startBtn').style.display=r.players.length>=2?'block':'none';if(!r.started)return;$('roundText').textContent=`${r.round}/${r.maxRounds}`;$('timerText').textContent=r.timeLeft;$('scoreA').textContent=r.scores.A;$('scoreB').textContent=r.scores.B;$('targetSwatch').style.background=rgbCss(r.target);$('targetText').textContent=rgbText(r.target);renderStatus(r);renderHand();renderReveal(r);renderEnd(r)}
function renderStatus(r){if(r.phase==='selecting'){const you=current.you.slot;$('status').textContent=r.selections[you]?'你已出牌，等待對方':'請選一張普通牌，或先使用搗亂牌'}else if(r.phase==='revealed')$('status').textContent='已揭示真實中心色';else if(r.phase==='ended')$('status').textContent='遊戲結束'}
function renderHand(){const hand=$('hand');hand.innerHTML='';const r=current.room,selected=r.selections[current.you.slot];current.hand.forEach(card=>{const el=makeCard(card,false);if(r.phase!=='selecting'||selected)el.style.opacity='.45';el.onclick=()=>{if(r.phase==='selecting'&&!selected)socket.emit('playCard',{code:r.code,cardId:card.id})};hand.appendChild(el)})}
function makeCard(card,revealed){const el=document.createElement('div');el.className='card';if(card.type==='trick'){el.classList.add('trick');el.style.background=stripeBg([255,223,85],[125,60,255],'normal');el.innerHTML=`<div class="trickBadge">搗亂</div><div class="cardName">${card.name}</div>`;return el}el.style.background=rgbCss(card.base);const circle=document.createElement('div');circle.className='circle';circle.style.background=rgbCss(card.center);const stripes=document.createElement('div');stripes.className='stripes';stripes.style.background=stripeBg(card.stripe,null,card.lineMode);const name=document.createElement('div');name.className='cardName';name.textContent=revealed?rgbText(card.center):card.name;el.appendChild(circle);if(!revealed)el.appendChild(stripes);el.appendChild(name);return el}
function stripeBg(stripe,second,mode){const w=mode==='thin'?6:12,g=mode==='thin'?14:24,c1=rgbCss(stripe);if(second)return`repeating-linear-gradient(90deg, ${c1} 0 ${w}px, ${rgbCss(second)} ${w}px ${g}px)`;return`repeating-linear-gradient(90deg, ${c1} 0 ${w}px, transparent ${w}px ${g}px)`}
function renderReveal(r){$('revealPanel').classList.toggle('hidden',r.phase!=='revealed');if(r.phase!=='revealed')return;const x=r.results[r.results.length-1];$('resultText').innerHTML=`目標：${rgbText(x.target)}<br>A：${x.A?rgbText(x.A.center)+'，距離 '+Number(x.A.distance).toFixed(1):'未出牌'}<br>B：${x.B?rgbText(x.B.center)+'，距離 '+Number(x.B.distance).toFixed(1):'未出牌'}<br><b>${x.resultText}</b>`;$('revealedCards').innerHTML='';['A','B'].forEach(slot=>{const box=document.createElement('div');box.innerHTML=`<h3>玩家 ${slot}</h3>`;const data=x[slot],card=document.createElement('div');card.className='trueCard';if(data){const circle=document.createElement('div');circle.className='circle';circle.style.background=rgbCss(data.center);const label=document.createElement('div');label.className='cardName';label.textContent=rgbText(data.center);card.appendChild(circle);card.appendChild(label)}else card.textContent='未出牌';box.appendChild(card);$('revealedCards').appendChild(box)})}
function renderEnd(r){$('endPanel').classList.toggle('hidden',r.phase!=='ended');if(r.phase!=='ended')return;$('winnerText').innerHTML=`<h3>贏家：${r.winner}</h3>`;$('researchText').innerHTML=buildResearch(r.results)}
function buildResearch(results){const distances=[],trick=[],normal=[];results.forEach(r=>['A','B'].forEach(s=>{const d=r[s]?.distance;if(d==null)return;distances.push(d);if(r[s].usedTrick)trick.push(d);else normal.push(d)}));const avg=a=>a.length?(a.reduce((x,y)=>x+y,0)/a.length).toFixed(1):'無資料';return`<table class="dataTable"><tr><th>指標</th><th>結果</th></tr><tr><td>整體平均 RGB 誤差</td><td>${avg(distances)}</td></tr><tr><td>使用搗亂牌回合平均誤差</td><td>${avg(trick)}</td></tr><tr><td>未使用搗亂牌平均誤差</td><td>${avg(normal)}</td></tr></table><p>可用於研究討論：背景條紋、對比與條紋粗細變化，是否增加玩家對中心色的判斷誤差。</p>`}
function downloadCSV(){const rows=[['round','target','player','center','distance','usedTrick','winner']];current.room.results.forEach(r=>['A','B'].forEach(s=>{const d=r[s];rows.push([r.round,r.target.join('-'),s,d?d.center.join('-'):'',d&&d.distance!=null?Number(d.distance).toFixed(3):'',d&&d.usedTrick?d.usedTrick:'',r.winner||''])}));const csv=rows.map(row=>row.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bezold_results_${current.room.code}.csv`;a.click()}
setInterval(()=>{if(current?.room?.phase==='selecting'){const t=Math.max(0,Number($('timerText').textContent)-1);$('timerText').textContent=t}},1000);
