const socket=io();let current=null;const $=id=>document.getElementById(id);
$("createBtn").onclick=()=>socket.emit("createRoom",{name:$("nameInput").value||"玩家A"});
$("joinBtn").onclick=()=>socket.emit("joinRoom",{code:$("roomInput").value,name:$("nameInput").value||"玩家B"});
$("startBtn").onclick=()=>socket.emit("startGame",{code:current.room.code});
$("nextBtn").onclick=()=>socket.emit("nextRound",{code:current.room.code});
$("downloadCsvBtn").onclick=()=>downloadCSV();
socket.on("created",d=>{$("roomInput").value=d.code});
socket.on("errorMessage",m=>$("message").textContent=m);
socket.on("state",s=>{current=s;render()});
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active")}
function rgbCss(r){return`rgb(${r[0]},${r[1]},${r[2]})`}function rgbText(r){return`RGB(${r[0]}, ${r[1]}, ${r[2]})`}
function render(){show("game");const r=current.room;$("roomCode").textContent=r.code;$("yourSlot").textContent=current.you?current.you.slot:"?";$("playersText").textContent="目前玩家："+r.players.map(p=>p.slot+" "+p.name).join("、");$("waitingPanel").classList.toggle("hidden",r.started);$("gamePanel").classList.toggle("hidden",!r.started);$("startBtn").style.display=r.players.length>=2?"block":"none";if(!r.started)return;$("roundText").textContent=`${r.round}/${r.maxRounds}`;$("timerText").textContent=r.timeLeft;$("scoreA").textContent=r.scores.A;$("scoreB").textContent=r.scores.B;$("targetSwatch").style.background=rgbCss(r.target);$("targetText").textContent=rgbText(r.target);renderStatus(r);renderHand();renderReveal(r);renderEnd(r)}
function renderStatus(r){const you=current.you.slot;if(r.phase==="selecting")$("status").textContent=r.selections[you]?"你已出牌，等待對方":"請選一張牌，或使用搗亂牌";else $("status").textContent=r.phase==="revealed"?"已揭示真實中心色":"遊戲結束"}
function renderHand(){const h=$("hand");h.innerHTML="";const r=current.room;const selected=r.selections[current.you.slot];current.hand.forEach(c=>{const el=makeCard(c,false);if(r.phase!=="selecting"||selected)el.style.opacity=".45";el.onclick=()=>{if(r.phase==="selecting"&&!selected)socket.emit("playCard",{code:r.code,cardId:c.id})};h.appendChild(el)})}
function makeCard(c,revealed){const el=document.createElement("div");el.className="card";if(c.type==="trick"){el.style.background=stripeBg([255,223,85]);el.innerHTML=`<div class="trickBadge">搗亂</div><div class="cardName">${c.name}</div>`;return el}el.style.background=rgbCss(c.base);const circle=document.createElement("div");circle.className="circle";circle.style.background=rgbCss(c.center);const stripes=document.createElement("div");stripes.className="stripes";stripes.style.background=stripeBg(c.stripe);const name=document.createElement("div");name.className="cardName";name.textContent=revealed?rgbText(c.center):c.name;el.appendChild(circle);if(!revealed)el.appendChild(stripes);el.appendChild(name);return el}
function stripeBg(s){return`repeating-linear-gradient(90deg, ${rgbCss(s)} 0 12px, transparent 12px 24px)`}
function renderReveal(r){$("revealPanel").classList.toggle("hidden",r.phase!=="revealed");if(r.phase!=="revealed")return;const x=r.results[r.results.length-1];$("resultText").innerHTML=`目標：${rgbText(x.target)}<br>A：${x.A?rgbText(x.A.center)+"，距離 "+x.A.distance.toFixed(1):"未出牌"}<br>B：${x.B?rgbText(x.B.center)+"，距離 "+x.B.distance.toFixed(1):"未出牌"}<br><b>${x.resultText}</b>`}
function renderEnd(r){$("endPanel").classList.toggle("hidden",r.phase!=="ended");if(r.phase!=="ended")return;$("winnerText").innerHTML=`<h3>贏家：${r.winner}</h3>`;$("researchText").innerHTML=`<p>可分析：RGB平均誤差、搗亂前後誤差、色彩同化造成的判斷偏差。</p>`}
function downloadCSV(){const rows=[["round","target","player","center","distance","winner"]];current.room.results.forEach(r=>["A","B"].forEach(p=>{const d=r[p];rows.push([r.round,r.target.join("-"),p,d?d.center.join("-"):"",d&&d.distance!=null?d.distance.toFixed(3):"",r.winner||""])}));const csv=rows.map(row=>row.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`bezold_${current.room.code}.csv`;a.click()}
setInterval(()=>{if(current?.room?.phase==="selecting")$("timerText").textContent=Math.max(0,Number($("timerText").textContent)-1)},1000);