
const socket=io();let current=null;const $=id=>document.getElementById(id);
$('createBtn').onclick=()=>{$('message').textContent='建立房間中...';socket.emit('createRoom',{name:$('nameInput').value||'玩家A'})};
$('joinBtn').onclick=()=>{$('message').textContent='加入房間中...';socket.emit('joinRoom',{code:$('roomInput').value,name:$('nameInput').value||'玩家B'})};
$('leaveBtn').onclick=()=>location.reload();
$('nextBtn').onclick=()=>socket.emit('nextRound',{code:current.room.code});
$('restartBtn').onclick=()=>socket.emit('restartRoom',{code:current.room.code});
$('downloadCsvBtn').onclick=()=>downloadCSV();
socket.on('created',d=>{$('roomInput').value=d.code});
socket.on('errorMessage',m=>{$('message').textContent=m});
socket.on('state',s=>{current=s;render()});
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function rgbCss(r){return`rgb(${r[0]},${r[1]},${r[2]})`}function rgbText(r){return`RGB(${r[0]}, ${r[1]}, ${r[2]})`}
function render(){show('game');let r=current.room;$('roomCode').textContent=r.code;$('yourSlot').textContent=current.you?current.you.slot:'?';$('playersText').textContent='目前玩家：'+r.players.map(p=>`${p.slot} ${p.name}`).join('、');$('waitingPanel').classList.toggle('hidden',r.phase!=='waiting');$('gamePanel').classList.toggle('hidden',r.phase==='waiting');if(r.phase==='waiting')return;$('roundText').textContent=`${r.round}/${r.maxRounds}`;$('timerText').textContent=r.timeLeft;$('scoreA').textContent=r.scores.A;$('scoreB').textContent=r.scores.B;if(r.target){$('targetSwatch').style.background=rgbCss(r.target);$('targetText').textContent=rgbText(r.target)}renderStatus(r);renderHand(r);renderReveal(r);renderEnd(r)}
function renderStatus(r){if(r.phase==='selecting'){$('status').textContent=r.selections[current.you.slot]?'你已出牌，等待對方':'請選一張顏色牌，或先使用搗亂牌'}else if(r.phase==='revealed')$('status').textContent='已揭示真實中心色';else if(r.phase==='ended')$('status').textContent='遊戲結束'}
function renderHand(r){let h=$('hand');h.innerHTML='';let selected=r.selections[current.you.slot];current.hand.forEach(card=>{let el=createCard(card,false);if(r.phase!=='selecting'||selected)el.classList.add('disabled');el.onclick=()=>{if(r.phase==='selecting'&&!selected)socket.emit('playCard',{code:r.code,cardId:card.id})};h.appendChild(el)})}
function createCard(card,revealed){let el=document.createElement('div');el.className='card';if(card.type==='trick'){el.style.background='repeating-linear-gradient(90deg,#ffdf55 0 12px,#7b3cff 12px 24px)';el.innerHTML=`<div class="trickBadge">搗亂</div><div class="cardName">${card.name}</div>`;return el}el.style.background=rgbCss(card.base);let circle=document.createElement('div');circle.className='circle';circle.style.background=rgbCss(card.center);let name=document.createElement('div');name.className='cardName';name.textContent=revealed?rgbText(card.center):card.name;el.appendChild(circle);if(!revealed){let stripes=document.createElement('div');stripes.className='stripes';stripes.style.background=stripeBg(card.stripe,card.lineMode);el.appendChild(stripes)}el.appendChild(name);return el}
function stripeBg(stripe,lineMode){let w=lineMode==='thin'?6:12,g=lineMode==='thin'?14:24;return`repeating-linear-gradient(90deg,${rgbCss(stripe)} 0 ${w}px,transparent ${w}px ${g}px)`}
function renderReveal(r){$('revealPanel').classList.toggle('hidden',r.phase!=='revealed');if(r.phase!=='revealed')return;let result=r.results[r.results.length-1];$('resultText').innerHTML=`目標：${rgbText(result.target)}<br>玩家 A：${result.A?rgbText(result.A.center)+'，距離 '+result.A.distance.toFixed(1):'未出牌'}<br>玩家 B：${result.B?rgbText(result.B.center)+'，距離 '+result.B.distance.toFixed(1):'未出牌'}<br><b>${result.resultText}</b>`;let box=$('revealCards');box.innerHTML='';['A','B'].forEach(slot=>{let wrap=document.createElement('div');wrap.innerHTML=`<h3>玩家 ${slot}</h3>`;let data=result[slot];if(data){wrap.appendChild(createCard({type:'normal',center:data.center,base:[247,247,247],stripe:[0,0,0],name:rgbText(data.center)},true))}else{let e=document.createElement('div');e.className='panel';e.textContent='未出牌';wrap.appendChild(e)}box.appendChild(wrap)})}
function renderEnd(r){$('endPanel').classList.toggle('hidden',r.phase!=='ended');if(r.phase!=='ended')return;$('revealPanel').classList.add('hidden');$('winnerText').innerHTML=`<h3>贏家：${r.winner}</h3>`;$('researchText').innerHTML=buildResearch(r.results)}
function buildResearch(results){let ds=[],td=[],nd=[];results.forEach(r=>['A','B'].forEach(slot=>{let d=r[slot];if(!d||d.distance==null)return;ds.push(d.distance);if(d.usedTricks&&d.usedTricks.length>0)td.push(d.distance);else nd.push(d.distance)}));let avg=a=>a.length?(a.reduce((x,y)=>x+y,0)/a.length).toFixed(1):'無資料';return`<table class="dataTable"><tr><th>研究指標</th><th>結果</th></tr><tr><td>整體平均 RGB 誤差</td><td>${avg(ds)}</td></tr><tr><td>使用搗亂牌者平均誤差</td><td>${avg(td)}</td></tr><tr><td>未使用搗亂牌者平均誤差</td><td>${avg(nd)}</td></tr></table><p>可作為小論研究：背景線條與色彩配置會影響玩家對中心色的判斷，形成色彩同化與知覺偏差。</p>`}
function downloadCSV(){let rows=[['round','target','player','center','distance','usedTricks','winner']];current.room.results.forEach(r=>['A','B'].forEach(slot=>{let d=r[slot];rows.push([r.round,r.target.join('-'),slot,d?d.center.join('-'):'',d&&d.distance!=null?d.distance.toFixed(3):'',d&&d.usedTricks?d.usedTricks.join('|'):'',r.winner||''])}));let csv=rows.map(row=>row.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');let blob=new Blob([csv],{type:'text/csv;charset=utf-8'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bezold_results_${current.room.code}.csv`;a.click()}
setInterval(()=>{if(current?.room?.phase==='selecting')$('timerText').textContent=Math.max(0,Number($('timerText').textContent)-1)},1000);
